services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: inventory-api
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./api:/app
    environment:
      WEB_DOCUMENT_ROOT: /app/public

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    network_mode: service:api
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME: http://localhost:8080
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: true
    command: start-dev
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password