security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        oidc:
            id: App\Security\Provider\UserProvider
        users:
            memory:
                users:
                    'hello.world@example.com': { password: 'q0hs9oDeLvJU5PnpKQNz' }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            stateless: false
            provider: oidc
            pattern: ^/
            oidc:
              user_identifier_property: preferred_username
              enable_end_session_listener: true
            access_token:
                token_handler:
                    oidc_user_info:
                        base_uri: '%keycloak.url%/realms/master/protocol/openid-connect/userinfo'
                        claim: preferred_username
            logout:
                path: /logout

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/login_check, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
